# Generated by Django 5.1.15 on 2026-07-30 06:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='슬러그')),
            ],
            options={
                'verbose_name': '맛집 태그',
                'verbose_name_plural': '맛집 태그 목록',
                'db_table': 'restaurants_restaurant_tag',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_restaurant_tag_name_ci')],
            },
        ),
    ]
