# Generated by Django 5.1.15 on 2026-07-30 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상호명')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='지번 주소')),
                ('road_address', models.CharField(blank=True, max_length=255, verbose_name='도로명 주소')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='위도')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='경도')),
                ('kakao_place_url', models.URLField(blank=True, verbose_name='카카오맵 링크')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='카카오 카테고리')),
                ('meal_time', models.CharField(choices=[('breakfast', '아침'), ('lunch', '점심'), ('dinner', '저녁'), ('all_day', '상시')], default='all_day', max_length=20, verbose_name='식사 시간대')),
                ('personal_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='개인 평점')),
                ('personal_review', models.CharField(blank=True, max_length=200, verbose_name='한줄 평')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.restauranttag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '맛집',
                'verbose_name_plural': '맛집 목록',
                'db_table': 'restaurants_restaurant',
                'ordering': ['-created_at'],
            },
        ),
    ]
