# Generated by Django 5.1.15 on 2026-07-30 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100, verbose_name='제보 상호명')),
                ('kakao_place_url', models.URLField(blank=True, verbose_name='카카오맵 링크')),
                ('message', models.TextField(blank=True, verbose_name='추천 이유')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='검토 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='제보자')),
            ],
            options={
                'verbose_name': '맛집 제보',
                'verbose_name_plural': '맛집 제보 목록',
                'db_table': 'restaurants_restaurant_suggestion',
                'ordering': ['-created_at'],
            },
        ),
    ]
