# Generated by Django 5.1.15 on 2026-06-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('team', '팀 프로젝트'), ('side', '사이드 프로젝트'), ('open_source', '오픈소스')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('status', models.CharField(max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('team_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('github_href', models.URLField(blank=True)),
                ('demo_href', models.URLField(blank=True)),
                ('title_href', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects_project',
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
    ]
