# Generated by Django 5.1.15 on 2026-06-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', '진행중'), ('completed', '완료'), ('archived', '중단')], max_length=20),
        ),
    ]
