# Generated by Django 5.1.15 on 2026-07-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_convert_project_category_status_to_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'ordering': ['order', 'id']},
        ),
    ]
