# Generated by Django 5.1.15 on 2026-08-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_demo_href_add_ios_android_extra_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='대표작 여부'),
        ),
    ]
