# Generated by Django 5.1.15 on 2026-07-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubContributionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('contribution_count', models.PositiveIntegerField(default=0, verbose_name='컨트리뷰션 수')),
            ],
            options={
                'verbose_name': 'GitHub 컨트리뷰션',
                'verbose_name_plural': 'GitHub 컨트리뷰션 목록',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='GithubProfileStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stars', models.PositiveIntegerField(default=0, verbose_name='총 star 수')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신 시각')),
            ],
            options={
                'verbose_name': 'GitHub 프로필 통계',
                'verbose_name_plural': 'GitHub 프로필 통계',
            },
        ),
    ]
