# Generated by Django 5.1.15 on 2026-07-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='이름')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=300, verbose_name='설명')),
                ('is_owner_only', models.BooleanField(default=False, verbose_name='소유자 전용')),
                ('url_name', models.CharField(max_length=100, verbose_name='연결할 URL name')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lab 도구',
                'verbose_name_plural': 'Lab 도구 목록',
                'db_table': 'site_tool',
                'ordering': ['order', 'title'],
            },
        ),
    ]
