# Generated by Django 5.1.15 on 2026-07-06 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjobconfig',
            name='cron_hour',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='scheduledjobconfig',
            name='cron_minute',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59)]),
        ),
    ]
