# Generated by Django 5.1.15 on 2026-07-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_scheduledjobconfig_cron_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjobconfig',
            name='cron_day_of_week',
            field=models.CharField(choices=[('*', '매일'), ('mon', '월요일'), ('tue', '화요일'), ('wed', '수요일'), ('thu', '목요일'), ('fri', '금요일'), ('sat', '토요일'), ('sun', '일요일')], default='*', max_length=3),
        ),
    ]
