# Generated by Django 5.1.15 on 2026-07-12 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scheduledjobconfig_cron_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjobconfig',
            name='fixed_hours',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scheduledjobconfig',
            name='fixed_minute',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='scheduledjobconfig',
            name='interval_hours',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1시간마다'), (2, '2시간마다'), (3, '3시간마다'), (4, '4시간마다'), (6, '6시간마다'), (8, '8시간마다'), (12, '12시간마다'), (24, '24시간마다')], null=True),
        ),
        migrations.AddField(
            model_name='scheduledjobconfig',
            name='interval_minute',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='scheduledjobconfig',
            name='schedule_mode',
            field=models.CharField(choices=[('interval', 'N시간마다'), ('fixed_times', '특정 시각')], default='fixed_times', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledjobconfig',
            name='cron_hour',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(23)]),
        ),
    ]
