# Generated by Django 5.1.15 on 2026-07-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scheduledjobconfig_fixed_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjobconfig',
            name='cron_day_of_week',
            field=models.CharField(default='*', max_length=30),
        ),
    ]
