# Generated by Django 5.1.15 on 2026-07-12 09:57

from django.db import migrations


def migrate_cron_hour_minute_forward(apps, schema_editor) -> None:
    """기존 cron_hour/cron_minute 값을 fixed_times 모드의 fixed_hours/fixed_minute로 이관한다.

    schedule_mode='interval'로 이미 설정된 행(Task 3 배포 이후 개발 환경에서 새로 시딩된 행 등)은
    cron_hour/cron_minute가 Task 1에서 추가된 무의미한 기본값(0)일 뿐이므로 건드리지 않는다 —
    실수로 의도된 interval 설정을 fixed_times로 되돌리지 않기 위한 방어.
    """
    ScheduledJobConfig = apps.get_model('core', 'ScheduledJobConfig')
    for config in ScheduledJobConfig.objects.exclude(schedule_mode='interval'):
        config.schedule_mode = 'fixed_times'
        config.fixed_hours = str(config.cron_hour)
        config.fixed_minute = config.cron_minute
        config.save(update_fields=['schedule_mode', 'fixed_hours', 'fixed_minute'])


def migrate_cron_hour_minute_backward(apps, schema_editor) -> None:
    # RemoveField의 reverse(재추가)는 컬럼만 복원하고 값은 복원하지 못하므로
    # 이 마이그레이션은 되돌리기를 지원하지 않는다. 필요 시 DB 백업에서 복원한다.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_scheduledjobconfig_cron_day_of_week'),
    ]

    operations = [
        migrations.RunPython(migrate_cron_hour_minute_forward, migrate_cron_hour_minute_backward),
        migrations.RemoveField(
            model_name='scheduledjobconfig',
            name='cron_hour',
        ),
        migrations.RemoveField(
            model_name='scheduledjobconfig',
            name='cron_minute',
        ),
    ]
