# Generated by Django 5.1.15 on 2026-07-12 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_scheduledjobconfig_cron_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjobconfig',
            name='fixed_minute',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='scheduledjobconfig',
            name='interval_minute',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59)]),
        ),
    ]
