# Generated by Django 5.1.15 on 2026-08-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_scheduledjobconfig_fixed_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjobconfig',
            name='interval_minutes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, '5분마다'), (10, '10분마다'), (15, '15분마다'), (30, '30분마다')], null=True),
        ),
        migrations.AlterField(
            model_name='scheduledjobconfig',
            name='schedule_mode',
            field=models.CharField(blank=True, choices=[('interval', 'N시간마다'), ('interval_minutes', 'N분마다'), ('fixed_times', '특정 시각')], default='fixed_times', max_length=20),
        ),
    ]
