# Generated by Django 5.1.15 on 2026-07-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('tagline', models.CharField(max_length=200, verbose_name='한 줄 소개')),
                ('avatar', models.ImageField(blank=True, upload_to='profile/avatar/', verbose_name='프로필 사진')),
                ('bio', models.TextField(blank=True, verbose_name='상세 소개(마크다운)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub 링크')),
                ('blog_url', models.URLField(blank=True, verbose_name='블로그/홈페이지 링크')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn 링크')),
                ('contribution_graph_url', models.URLField(blank=True, verbose_name='3D 컨트리뷰션 그래프 이미지 URL')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필',
            },
        ),
        migrations.CreateModel(
            name='VisitorCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='누적 방문 수')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신 시각')),
            ],
            options={
                'verbose_name': '방문자 카운터',
                'verbose_name_plural': '방문자 카운터',
            },
        ),
    ]
