# Generated by Django 5.1.15 on 2026-07-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='활동명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='기간')),
                ('link', models.URLField(blank=True, verbose_name='관련 링크')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '활동',
                'verbose_name_plural': '활동 목록',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('work', '직장'), ('education', '학력'), ('award', '수상')], max_length=20, verbose_name='분류')),
                ('organization', models.CharField(max_length=100, verbose_name='기관명')),
                ('role', models.CharField(max_length=100, verbose_name='역할/직책/학위')),
                ('period_start', models.DateField(verbose_name='시작일')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='종료일(재직/재학 중이면 비움)')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '이력',
                'verbose_name_plural': '이력 목록',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='자격증명')),
                ('issuer', models.CharField(max_length=100, verbose_name='발급기관')),
                ('acquired_date', models.DateField(verbose_name='취득일')),
                ('credential_number', models.CharField(blank=True, max_length=100, verbose_name='자격증 번호')),
                ('credential_url', models.URLField(blank=True, verbose_name='커리큘럼/검증 링크')),
                ('badge_image', models.ImageField(blank=True, upload_to='profile/certification/', verbose_name='배지 이미지')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '자격증',
                'verbose_name_plural': '자격증 목록',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='PullRequestHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('repo_name', models.CharField(max_length=200, verbose_name='저장소 이름')),
                ('pr_url', models.URLField(verbose_name='PR 링크')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '대표 PR',
                'verbose_name_plural': '대표 PR 목록',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Database'), ('infra', 'Infra'), ('tool', 'Tool'), ('etc', 'ETC')], max_length=20, verbose_name='분류')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('icon_slug', models.CharField(blank=True, max_length=50, verbose_name='Simple Icons 슬러그')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '기술스택',
                'verbose_name_plural': '기술스택 목록',
                'ordering': ('category', 'order'),
            },
        ),
    ]
