# Generated by Django 5.1.15 on 2026-07-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_activity_career_certification_pullrequesthighlight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon_slug',
            field=models.CharField(blank=True, max_length=255, verbose_name='Simple Icons 슬러그 또는 아이콘 URL'),
        ),
    ]
