# Generated by Django 5.1.15 on 2026-07-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_alter_skill_icon_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='credential_number',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='credential_url',
        ),
    ]
