# Generated by Django 5.1.15 on 2026-07-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_remove_certification_credential_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon_slug',
            field=models.CharField(blank=True, max_length=255, verbose_name='아이콘 슬러그(벤더링된 세트 기준)'),
        ),
    ]
