# Generated by Django 5.1.15 on 2026-08-09 07:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_activity_start_year_end_year_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='activities/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'ppt', 'pptx', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='첨부파일')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='표시명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='profile.activity')),
            ],
            options={
                'verbose_name': '활동 첨부파일',
                'verbose_name_plural': '활동 첨부파일 목록',
                'ordering': ('order',),
            },
        ),
    ]
