# Generated by Django 5.1.15 on 2026-08-09 13:48

import apps.profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_remove_activity_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='links',
            field=models.JSONField(blank=True, default=list, help_text='예: [{"type": "github", "url": "https://..."}]. type은 official/github/youtube/instagram/linkedin/presentation/article/other 중 하나.', validators=[apps.profile.models.validate_activity_links], verbose_name='관련 링크 목록'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('end_year__isnull', True), ('end_year__gte', models.F('start_year')), _connector='OR'), name='activity_end_year_gte_start_year'),
        ),
    ]
