# Generated by Django 5.1.15 on 2026-10-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_alter_activity_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='방문 수')),
            ],
            options={
                'verbose_name': '일자별 방문자',
                'verbose_name_plural': '일자별 방문자',
                'ordering': ('-date',),
            },
        ),
    ]
