# Generated by Django 5.1.15 on 2026-10-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_add_daily_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorCounter',
        ),
    ]
