# Generated by Django 5.1.15 on 2026-07-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='요약')),
                ('content', models.TextField(verbose_name='본문 (Markdown)')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='태그')),
                ('is_published', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='발행일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '블로그 포스트',
                'verbose_name_plural': '블로그 포스트 목록',
                'db_table': 'blog_post',
                'ordering': ['-published_at'],
            },
        ),
    ]
