# Generated by Django 5.1.15 on 2026-08-20 09:28

import apps.clubs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='동아리명')),
                ('homepage_url', models.URLField(verbose_name='모집공고 페이지 URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='감시 활성화')),
                ('discord_webhook_url', models.URLField(blank=True, default='', validators=[apps.clubs.models.validate_discord_webhook_url], verbose_name='Discord 웹훅 URL')),
                ('is_recruiting_now', models.BooleanField(default=False, verbose_name='최근 확인 시 모집 중 여부')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 확인 시각')),
                ('consecutive_failure_count', models.PositiveSmallIntegerField(default=0, verbose_name='연속 실패 횟수')),
                ('failure_alert_sent', models.BooleanField(default=False, verbose_name='실패 알림 발송 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시각')),
            ],
            options={
                'verbose_name': '동아리 모집 감시',
                'verbose_name_plural': '동아리 모집 감시 목록',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_start', models.DateField(blank=True, null=True, verbose_name='지원 시작일')),
                ('application_end', models.DateField(blank=True, null=True, verbose_name='지원 종료일')),
                ('apply_url', models.URLField(blank=True, default='', verbose_name='지원 링크')),
                ('evidence_quote', models.TextField(verbose_name='판별 근거 문장')),
                ('notify_succeeded', models.BooleanField(default=False, verbose_name='알림 발송 성공 여부')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='감지 시각')),
                ('tracked_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='clubs.trackedclub', verbose_name='감시 대상')),
            ],
            options={
                'verbose_name': '모집 감지 이력',
                'verbose_name_plural': '모집 감지 이력 목록',
                'ordering': ('-detected_at',),
            },
        ),
    ]
