# Generated by Django 5.1.15 on 2026-07-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('chatbot', '사이트 챗봇')], max_length=50, verbose_name='기능')),
                ('name', models.CharField(max_length=100, verbose_name='프롬프트 이름')),
                ('system_prompt', models.TextField(verbose_name='시스템 프롬프트')),
                ('model', models.CharField(max_length=100, verbose_name='SUH-AIder 모델명')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': 'AI 프롬프트',
                'verbose_name_plural': 'AI 프롬프트 목록',
                'ordering': ('feature', '-updated_at'),
            },
        ),
    ]
