# Generated by Django 5.1.15 on 2026-07-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('feature',), name='unique_active_prompt_template_per_feature'),
        ),
    ]
