# Generated by Django 5.1.15 on 2026-08-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_prompttemplate_unique_active_prompt_template_per_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='feature',
            field=models.CharField(choices=[('chatbot', '사이트 챗봇'), ('github_trending_summary', 'GitHub 트렌딩 요약')], max_length=50, verbose_name='기능'),
        ),
    ]
