# Generated by Django 5.1.15 on 2026-08-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_prompttemplate_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='feature',
            field=models.CharField(choices=[('chatbot', '사이트 챗봇'), ('github_trending_summary', 'GitHub 트렌딩 요약'), ('club_recruitment_detection', '동아리 모집 여부 판별')], max_length=50, verbose_name='기능'),
        ),
    ]
