# Generated by Django 5.1.15 on 2026-09-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LectureDownloadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('lecture_id', models.CharField(max_length=20)),
                ('lecture_title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', '대기'), ('running', '진행중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=10)),
                ('file_relative_path', models.CharField(blank=True, default='', max_length=300)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lecture_download_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
