# Generated by Django 5.1.15 on 2026-08-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='자격증명')),
                ('issuer', models.CharField(max_length=100, verbose_name='발급기관')),
                ('category', models.CharField(choices=[('national_tech', '국가기술자격'), ('it_private', 'IT 민간자격'), ('language', '어학'), ('etc', '기타')], max_length=20, verbose_name='분류')),
                ('official_url', models.URLField(blank=True, default='', verbose_name='공식 사이트')),
                ('crawler_type', models.CharField(max_length=30, verbose_name='크롤러 타입')),
                ('crawler_source_id', models.CharField(blank=True, default='', max_length=100, verbose_name='크롤러 소스 식별자')),
                ('is_always_open', models.BooleanField(default=False, verbose_name='상시 접수 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='추적 활성화')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '자격증',
                'verbose_name_plural': '자격증 목록',
                'ordering': ('order', 'name'),
            },
        ),
    ]
