# Generated by Django 5.1.15 on 2026-08-13 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=50, verbose_name='회차명')),
                ('registration_start', models.DateField(verbose_name='원서접수 시작일')),
                ('registration_end', models.DateField(verbose_name='원서접수 마감일')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='시험일')),
                ('result_announcement_date', models.DateField(blank=True, null=True, verbose_name='합격자 발표일')),
                ('source_url', models.URLField(blank=True, default='', verbose_name='출처 링크')),
                ('registration_open_notified', models.BooleanField(default=False, verbose_name='접수 시작 알림 발송 여부')),
                ('registration_deadline_notified', models.BooleanField(default=False, verbose_name='접수 마감 임박 알림 발송 여부')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='certifications.certificationdefinition', verbose_name='자격증')),
            ],
            options={
                'verbose_name': '시험 일정',
                'verbose_name_plural': '시험 일정 목록',
                'ordering': ('registration_start',),
                'constraints': [models.UniqueConstraint(fields=('certification', 'round_name'), name='unique_certification_round')],
            },
        ),
    ]
