# Generated by Django 5.1.15 on 2026-08-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_examschedule'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examschedule',
            constraint=models.CheckConstraint(condition=models.Q(('registration_end__gte', models.F('registration_start'))), name='exam_schedule_registration_end_gte_start'),
        ),
    ]
