# Generated by Django 5.1.15 on 2026-08-13 11:44

import apps.certifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_examschedule_exam_schedule_registration_end_gte_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_webhook_url', models.URLField(blank=True, default='', validators=[apps.certifications.models.validate_discord_webhook_url], verbose_name='Discord 웹훅 URL')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '자격증 알림 설정',
                'verbose_name_plural': '자격증 알림 설정',
            },
        ),
    ]
