# Generated by Django 5.1.15 on 2026-08-11 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaScreenWatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_screen', models.CharField(choices=[('cgv_yongsan_imax', 'CGV 용산아이파크몰 IMAX'), ('lotte_jamsil_superplex', '롯데시네마 잠실 월드타워 수퍼플렉스')], max_length=30, unique=True, verbose_name='상영관')),
                ('consecutive_failure_count', models.PositiveSmallIntegerField(default=0, verbose_name='연속 실패 횟수')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='실패 알림 발송 여부')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '상영관 감시 상태',
                'verbose_name_plural': '상영관 감시 상태 목록',
            },
        ),
        migrations.CreateModel(
            name='NowShowingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_screen', models.CharField(choices=[('cgv_yongsan_imax', 'CGV 용산아이파크몰 IMAX'), ('lotte_jamsil_superplex', '롯데시네마 잠실 월드타워 수퍼플렉스')], max_length=30, verbose_name='상영관')),
                ('movie_code', models.CharField(max_length=200, verbose_name='영화 코드')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('is_currently_showing', models.BooleanField(default=True, verbose_name='현재 상영 중')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '지금 상영 중인 영화',
                'verbose_name_plural': '지금 상영 중인 영화 목록',
                'unique_together': {('cinema_screen', 'movie_code')},
            },
        ),
        migrations.CreateModel(
            name='TrackedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_screen', models.CharField(choices=[('cgv_yongsan_imax', 'CGV 용산아이파크몰 IMAX'), ('lotte_jamsil_superplex', '롯데시네마 잠실 월드타워 수퍼플렉스')], max_length=30, verbose_name='상영관')),
                ('is_active', models.BooleanField(default=True, verbose_name='감시 활성화')),
                ('discord_webhook_url', models.URLField(verbose_name='Discord 웹훅 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracked_movies', to='cinema.nowshowingmovie', verbose_name='영화')),
            ],
            options={
                'verbose_name': '영화 감시',
                'verbose_name_plural': '영화 감시 목록',
            },
        ),
        migrations.CreateModel(
            name='OpenedShowDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField(verbose_name='상영일')),
                ('showtimes', models.JSONField(default=list, verbose_name='상영 시간 목록')),
                ('notify_succeeded', models.BooleanField(default=False, verbose_name='알림 발송 성공 여부')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('tracked_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_dates', to='cinema.trackedmovie', verbose_name='감시 대상')),
            ],
            options={
                'verbose_name': '오픈된 상영일',
                'verbose_name_plural': '오픈된 상영일 목록',
                'unique_together': {('tracked_movie', 'show_date')},
            },
        ),
    ]
