# Generated by Django 5.1.15 on 2026-08-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JamsilSuperplexWatch',
            fields=[
            ],
            options={
                'verbose_name': '롯데 잠실 수퍼플렉스 감시',
                'verbose_name_plural': '롯데 잠실 수퍼플렉스 감시 목록',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cinema.trackedmovie',),
        ),
        migrations.CreateModel(
            name='YongsanImaxWatch',
            fields=[
            ],
            options={
                'verbose_name': 'CGV 용산 IMAX 감시',
                'verbose_name_plural': 'CGV 용산 IMAX 감시 목록',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cinema.trackedmovie',),
        ),
    ]
