# Generated by Django 5.1.15 on 2026-08-12 03:29

import apps.cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_jamsilsuperplexwatch_yongsanimaxwatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedmovie',
            name='discord_webhook_url',
            field=models.URLField(validators=[apps.cinema.models.validate_discord_webhook_url], verbose_name='Discord 웹훅 URL'),
        ),
    ]
