# Generated by Django 5.1.15 on 2026-06-10 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='사이트명')),
                ('url', models.URLField(verbose_name='목록 URL')),
                ('crawler_type', models.CharField(max_length=50, verbose_name='크롤러 타입')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '공지 출처',
                'verbose_name_plural': '공지 출처 목록',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=100, verbose_name='원본 글 ID')),
                ('title', models.CharField(max_length=500, verbose_name='제목')),
                ('url', models.URLField(verbose_name='상세 URL')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='게시일')),
                ('is_notified', models.BooleanField(default=False, verbose_name='알림 발송 여부')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='알림 발송 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='notifications.noticesource', verbose_name='출처')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항 목록',
                'unique_together': {('source', 'article_id')},
            },
        ),
    ]
