# Generated by Django 5.1.15 on 2026-06-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticesource',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='텔레그램 채팅방 ID'),
        ),
    ]
