# Generated by Django 5.1.15 on 2026-07-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_noticesource_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticesource',
            name='telegram_chat_id',
        ),
        migrations.AddField(
            model_name='noticesource',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='noticesource',
            name='discord_webhook_url',
            field=models.URLField(blank=True, default='', verbose_name='Discord 웹훅 URL'),
        ),
    ]
